name: 'Conventional Labeler'
description: 'A Pull request labeler using conventional commit standard'
branding:
  icon: align-center
  color: green

inputs:
  access_token:
    description: Github Access Token to access and modify your pr's label
    required: true
  strict:
    description: Validate all commit messages use conventional commit standard
    required: false
    default: "true"
outputs:
  labels:
    description: Generated space delimited labels for your pull request.
  labels_list:
    description: Generated labels for your pull request in list form.
runs:
  using: 'node16'
  main: 'dist/index.js'